train_input:
  data_args: 
    batch_size: 16
    group_batch: 1
    with_force: false
    with_orbital: true
    conv_filter: true
    conv_name: conv
  preprocess_args:
    preshift: false
    prescale: false
    prefit_ridge: 1e1
    prefit_trainable: false
  train_args: 
    decay_rate: 0.75
    decay_steps: 1000
    display_epoch: 100
    force_factor: 0
    orbital_factor: 0.5
    n_epoch: 5000
    start_lr: 0.0004
